### ISSUE TITLE
Cleartext HTTP traffic to ws.detectlanguage.com not permitted

### ISSUE THREAD

**Issue by TheItalianNerd** [detectlanguage/detectlanguage-java#10]
To test this API, i copied and pasted the "template" from the documentation (except the API key of course) and I got this error

**Comment by laurynas** [comment]
@TheItalianNerd I guess the error is caused by your network restrictions (or maybe ISP restrictions). 
I suggest to enable SSL mode:

```java
DetectLanguage.ssl = true;
```
