### ISSUE TITLE
APIError

### ISSUE THREAD

**Issue by PaddyWagon** [detectlanguage/detectlanguage-java#4]
Hey, I'm currently trying to make a minecraft spigot plugin using your API, and I'm running into a wall. 

```
public static String englishOnly(String message){

        DetectLanguage.apiKey = "";

        String language = DetectLanguage.simpleDetect(message);

        if(language.equals("en"))
        {
            return "en";
        }
        return "";
    }
```

The "DetectLanguage.simpleDetect(message);" gives the APIError unhandled exception and I'm not entirely sure how to remedy this, I'd greatly appreciate any feedback on the issue. 

Thank you for your time, 

Regards, 
Paddy

@laurynas

**Comment by laurynas** [comment]
Hey @PaddyWagon, your code looks ok. Please check if you have network connection and can access `http://ws.detectlanguage.com`. 

Also you should reset your API key, because it is private ant you have published it in this issue. You should not share your API key. You can reset your API key at https://detectlanguage.com/ dashboard.

**Comment by PaddyWagon** [comment]
I'm able to connect to `http://ws.detectlanguage.com` and thank you for letting me know about the api key, I've edited the original issue. 

When I try to build it, I get this error `https://i.imgur.com/p1gQULJ.png` but if I add the exception to the method signature, it simply won't run the method. Any ideas on what I should do pertaining to the actual code?

I appreciate the quick response!

Thank you, 
Paddy

**Comment by laurynas** [comment]
You can catch the exception and handle like this:

```java
try {
    language = DetectLanguage.simpleDetect(message);
} catch (APIError e) {
    System.err.println("DetectLanguage APIError: " + e.getMessage());
    return "";
}
```

or you could add `throws APIError` to your method and handled it in the caller.
https://docs.oracle.com/javase/tutorial/essential/exceptions/declaring.html

By the way, you should reset you API key again, because it is visible it the screenshot :)

**Comment by PaddyWagon** [comment]
Thank you, reset the key. I created the method just to test and I'm still having trouble, I did this : 
```
    public static String englishOnly(String message) {

        DetectLanguage.apiKey = "key";

        try {
            String language = DetectLanguage.simpleDetect(message);
        } catch (APIError apiError) {
            return "Test";
        }
        return "Test2";
    }
```
I called it with this : 
```
    @org.bukkit.event.EventHandler
    public void onTranslate(AsyncPlayerChatEvent event)
    {
        String message = event.getMessage();
        Player player = event.getPlayer();

        player.sendMessage(englishOnly(message));

        event.setCancelled(true);
    }
```
In-game it triggers the AsyncPlayerChatEvent, but rather than sending the string in `player.sendMessage(englishOnly(message));` it simply does nothing, as in it doesn't send "Test" or "Test2" in chat. I'm not sure if you're familiar with spigot api but that's a brief rundown on what's happening. What exactly causes the "APIError"?

Thank you, 
Paddy

**Comment by laurynas** [comment]
Sorry, missed your message. I assume you found the issue.

**Comment by PaddyWagon** [comment]
I've yet to find the solution but the project has been discontinued due to changes in the network I help out with. If you know why it was giving the error provided, I'd appreciate it if you can explain.

Regards, 
Paddy
