### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by adnanafzal565** [detectlanguage/detectlanguage-java#6]
java.lang.RuntimeException: java.net.SocketTimeoutException: failed to connect to ws.detectlanguage.com/109.235.67.238 (port 80) after 3000ms

**Comment by laurynas** [comment]
Hi, looks like a network issue. Are you still experiencing it?

**Comment by adnanafzal565** [comment]
No, not client's network issue. But if the server does not response within 30 seconds, then it was throwing this exception.

It was fixed by just updating the library.
