### ISSUE TITLE
Identify language by last word in the sentence

### ISSUE THREAD

**Issue by ZheniaYarmaliuk** [detectlanguage/detectlanguage-java#9]
Hi Team,
When I try to identify language by sentence "Crea una password".  DetectLanguage.detect get English.
When I try to with "Crea una" DetectLanguage.detect has 3 options. I guess it works by the last word. When I tried set text as [] array,
the result was the same: English. Expected: Italian. Could you please review it?

**Comment by laurynas** [comment]
Hi Zhenia,
such text is text is tricky, because `password` is actually an English word.
